# Generated by Django 3.2.7 on 2021-10-01 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_auto_20211001_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
